### ISSUE TITLE
Doesnt seem to work with ChatGPT

### ISSUE THREAD

**Issue by YeetoC** [codespin-ai/codespin-chrome-extension#1]
Hello,

it works fine on claude but the button to add files doesnt show up on chatgpt.

I am using the Chrome Extension Store version but it was the same with the manual install. 

I apprechiate any help :)

**Comment by YeetoC** [comment]
![image](https://github.com/user-attachments/assets/30e9a1c4-a7ca-4a77-8f5f-e1cb8ae19483)
![image](https://github.com/user-attachments/assets/63a34815-31e7-446a-9fdc-19a3b59c3592)

For comparison

**Comment by jeswin** [comment]
I'll look at it today.

**Comment by jeswin** [comment]
I am not able to reproduce it with the latest code.

Can you try this zip please? 
[codespin-plugin-1_0_5.zip](https://github.com/user-attachments/files/18159062/codespin-plugin-1_0_5.zip)

![image](https://github.com/user-attachments/assets/4b0d7c0b-eb49-4fa2-bfe3-6fc1cafee355)

I'm happy to help debug this. This is the file where we attach the button src/chatGPT/components/ChatGPTInboundButton.tsx

**Comment by YeetoC** [comment]
Thank you for looking into it. 

With the zip you attached it still doesnt seem to work on chatgpt. Claude works fine. 

![image](https://github.com/user-attachments/assets/00967706-810f-4aa5-b595-a3301c3f5d52)

**Comment by jeswin** [comment]
Ahh, I may know what's causing the issue.

```ts
async function attachInboundButton() {
  if (!document.querySelector("codespin-chatgpt-inbound-button")) {
    const searchTheWebButton = document.querySelector(
      'button[aria-label="Search the web"]'
    );

    // Ensure the button is found before proceeding
    if (searchTheWebButton) {
      // Create a new custom element
      const inboundButton = createNode(
        <codespin-chatgpt-inbound-button></codespin-chatgpt-inbound-button>
      );

      // Insert the custom element right after the button
      searchTheWebButton.parentElement?.parentElement?.insertAdjacentElement(
        "afterend",
        inboundButton as Element
      );
    }
  }
}
```

I am trying to insert the button next to something that already exists (searchTheWebButton). Can you see why it's working for me but not for you? :)

I'll roll out a fix today.

**Comment by jeswin** [comment]
I have fixed it. Can you pull the latest code and see if it works please?

Once you confirm that, I'll push the change the Chrome WebStore.

**Comment by YeetoC** [comment]
Latest code works!

**Comment by YeetoC** [comment]
Issue has been fixed
